//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.20 at 03:03:39 PM EDT 
//


package org.scigap.us3.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}experimentid" minOccurs="0"/>
 *         &lt;element ref="{}hostname" minOccurs="0"/>
 *         &lt;element ref="{}processorcount" minOccurs="0"/>
 *         &lt;element ref="{}hostcount" minOccurs="0"/>
 *         &lt;element ref="{}queuename" minOccurs="0"/>
 *         &lt;element ref="{}walltime" minOccurs="0"/>
 *         &lt;element ref="{}gfaclocation" minOccurs="0"/>
 *         &lt;element ref="{}userdn" minOccurs="0"/>
 *         &lt;element ref="{}brokerURL" minOccurs="0"/>
 *         &lt;element ref="{}serviceName" minOccurs="0"/>
 *         &lt;element ref="{}workflowName" minOccurs="0"/>
 *         &lt;element ref="{}cluster" minOccurs="0"/>
 *         &lt;element ref="{}us3_db" minOccurs="0"/>
 *         &lt;element ref="{}mgroupcount" minOccurs="0"/>
 *         &lt;element ref="{}global_db" minOccurs="0"/>
 *         &lt;element ref="{}global_host" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "experimentid",
    "hostname",
    "processorcount",
    "hostcount",
    "queuename",
    "walltime",
    "gfaclocation",
    "userdn",
    "brokerURL",
    "serviceName",
    "workflowName",
    "cluster",
    "us3Db",
    "mgroupcount",
    "globalDb",
    "globalHost"
})
@XmlRootElement(name = "Header")
public class Header {

    protected String experimentid;
    protected String hostname;
    protected Integer processorcount;
    protected Integer hostcount;
    protected String queuename;
    protected Integer walltime;
    protected String gfaclocation;
    protected String userdn;
    protected String brokerURL;
    protected String serviceName;
    protected String workflowName;
    protected String cluster;
    @XmlElement(name = "us3_db")
    protected String us3Db;
    protected String mgroupcount;
    @XmlElement(name = "global_db")
    protected String globalDb;
    @XmlElement(name = "global_host")
    protected String globalHost;

    /**
     * Gets the value of the experimentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperimentid() {
        return experimentid;
    }

    /**
     * Sets the value of the experimentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperimentid(String value) {
        this.experimentid = value;
    }

    /**
     * Gets the value of the hostname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * Sets the value of the hostname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostname(String value) {
        this.hostname = value;
    }

    /**
     * Gets the value of the processorcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProcessorcount() {
        return processorcount;
    }

    /**
     * Sets the value of the processorcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProcessorcount(Integer value) {
        this.processorcount = value;
    }

    /**
     * Gets the value of the hostcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHostcount() {
        return hostcount;
    }

    /**
     * Sets the value of the hostcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHostcount(Integer value) {
        this.hostcount = value;
    }

    /**
     * Gets the value of the queuename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueuename() {
        return queuename;
    }

    /**
     * Sets the value of the queuename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueuename(String value) {
        this.queuename = value;
    }

    /**
     * Gets the value of the walltime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWalltime() {
        return walltime;
    }

    /**
     * Sets the value of the walltime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWalltime(Integer value) {
        this.walltime = value;
    }

    /**
     * Gets the value of the gfaclocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGfaclocation() {
        return gfaclocation;
    }

    /**
     * Sets the value of the gfaclocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGfaclocation(String value) {
        this.gfaclocation = value;
    }

    /**
     * Gets the value of the userdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserdn() {
        return userdn;
    }

    /**
     * Sets the value of the userdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserdn(String value) {
        this.userdn = value;
    }

    /**
     * Gets the value of the brokerURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerURL() {
        return brokerURL;
    }

    /**
     * Sets the value of the brokerURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerURL(String value) {
        this.brokerURL = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the workflowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * Sets the value of the workflowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowName(String value) {
        this.workflowName = value;
    }

    /**
     * Gets the value of the cluster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCluster() {
        return cluster;
    }

    /**
     * Sets the value of the cluster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCluster(String value) {
        this.cluster = value;
    }

    /**
     * Gets the value of the us3Db property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUs3Db() {
        return us3Db;
    }

    /**
     * Sets the value of the us3Db property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUs3Db(String value) {
        this.us3Db = value;
    }

    /**
     * Gets the value of the mgroupcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgroupcount() {
        return mgroupcount;
    }

    /**
     * Sets the value of the mgroupcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgroupcount(String value) {
        this.mgroupcount = value;
    }

    /**
     * Gets the value of the globalDb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalDb() {
        return globalDb;
    }

    /**
     * Sets the value of the globalDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalDb(String value) {
        this.globalDb = value;
    }

    /**
     * Gets the value of the globalHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalHost() {
        return globalHost;
    }

    /**
     * Sets the value of the globalHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalHost(String value) {
        this.globalHost = value;
    }

}
